In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('customers.csv')

In [22]:
display(df)

,customer_id,full_name,email,city,age,lifetime_value,membership_tier,signup_date,is_active
0,1,Sarah Smith,sarah.smith1@example.com,Waterbury,33,1154.89,Bronze,2026-02-27,True
1,2,Melissa Smith,melissa.smith2@example.com,East Windsor,31,1201.67,Bronze,2022-03-03,True
2,3,Melissa Brown,melissa.brown3@example.com,Waterbury,69,4353.04,Silver,2024-07-08,False
3,4,Matthew Jones,matthew.jones4@example.com,Stamford,66,1716.14,Bronze,2022-11-15,False
4,5,Sarah Garcia,sarah.garcia5@example.com,Waterbury,69,265.08,Platinum,2023-12-06,True
...,...,...,...,...,...,...,...,...,...
95,96,Jane Jones,jane.jones96@example.com,East Windsor,70,373.45,Platinum,2024-09-05,True
96,97,Jane Williams,jane.williams97@example.com,Waterbury,23,4969.89,Bronze,2022-11-02,False
97,98,Jessica Wilson,jessica.wilson98@example.com,Danbury,46,1521.90,Platinum,2024-02-19,False
98,99,Jane Moore,jane.moore99@example.com,East Windsor,66,1078.55,Silver,2026-02-24,False
99,100,Michael Williams,michael.williams100@example.com,New Haven,53,421.57,Bronze,2023-05-07,False

In [23]:
display(len(df))

100

In [24]:
df.dropna()
df.fillna(0)

,customer_id,full_name,email,city,age,lifetime_value,membership_tier,signup_date,is_active
0,1,Sarah Smith,sarah.smith1@example.com,Waterbury,33,1154.89,Bronze,2026-02-27,True
1,2,Melissa Smith,melissa.smith2@example.com,East Windsor,31,1201.67,Bronze,2022-03-03,True
2,3,Melissa Brown,melissa.brown3@example.com,Waterbury,69,4353.04,Silver,2024-07-08,False
3,4,Matthew Jones,matthew.jones4@example.com,Stamford,66,1716.14,Bronze,2022-11-15,False
4,5,Sarah Garcia,sarah.garcia5@example.com,Waterbury,69,265.08,Platinum,2023-12-06,True
...,...,...,...,...,...,...,...,...,...
95,96,Jane Jones,jane.jones96@example.com,East Windsor,70,373.45,Platinum,2024-09-05,True
96,97,Jane Williams,jane.williams97@example.com,Waterbury,23,4969.89,Bronze,2022-11-02,False
97,98,Jessica Wilson,jessica.wilson98@example.com,Danbury,46,1521.90,Platinum,2024-02-19,False
98,99,Jane Moore,jane.moore99@example.com,East Windsor,66,1078.55,Silver,2026-02-24,False
99,100,Michael Williams,michael.williams100@example.com,New Haven,53,421.57,Bronze,2023-05-07,False

In [ ]:
df = df[df['customer_id'] < 4]
display(df)

,customer_id,full_name,email,city,age,lifetime_value,membership_tier,signup_date,is_active
0,1,Sarah Smith,sarah.smith1@example.com,Waterbury,33,1154.89,Bronze,2026-02-27,True
1,2,Melissa Smith,melissa.smith2@example.com,East Windsor,31,1201.67,Bronze,2022-03-03,True
2,3,Melissa Brown,melissa.brown3@example.com,Waterbury,69,4353.04,Silver,2024-07-08,False

In [ ]:
# How do you remove duplicate rows?
df.drop_duplicates()

# What is the use of apply()?
df['Salary'] = df['Salary'].apply(lambda x: x*1.1)

# How can you rename columns?
df.rename(columns={'old_name':'new_name'})

# How do you sort a DataFrame?
df.sort_values(by='Salary', ascending=False)

# What is the difference between concat() and merge()?
Answer:
- concat() stacks DataFrames.
- merge() joins DataFrames using keys.

# How do you find unique values?
df['Department'].unique()